version: '3.8'

services:
  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-v:/data 

  discord-db:
    image: postgres
    container_name: discord-db
    ports:
      - "5479:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=discord

volumes:
  redis-v:
  pg-data:
